version: 1.0.{build}
image: Visual Studio 2017
nuget:
  account_feed: true
  project_feed: true
build:
  verbosity: minimal
build_script:
- cmd: ./build.cmd
artifacts:
- path: 'artifacts/**.nupkg'
- path: 'artifacts/ReleaseNotes.md'
